package My_form;



import java.awt.HeadlessException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

        import java.util.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import my_classess.Book;
import my_classess.func_Class;


/**
 *
 * @author Admin
 */
public class IssueBookForm extends javax.swing.JFrame {

    /**
     * Creates new form AddBookForm
     */
    
    
     my_classess.func_Class func=new my_classess.func_Class();
     my_classess.Member member = new my_classess.Member();
      my_classess.Book book = new my_classess.Book() ;
      my_classess.Issue_Book  issue=new my_classess.Issue_Book();
      
      boolean book_Exist = false;
       boolean member_Exist = false;
    
      
     
    public IssueBookForm() {
        initComponents();
        
        
        
        this.setLocationRelativeTo(null);
         
           Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3,3, new java.awt.Color(108,122,137));
        jPanel1.setBorder(panelHeaderBorder);
        
        func.displayImage(90, 60, "/My_images/members1.png", jLabel_formtitle);
        
        fillJcomboboxWithGenres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel_formtitle = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_Issue = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jButton_SelectBook_ = new javax.swing.JButton();
        jLabel_BookName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_MemberFullName = new javax.swing.JLabel();
        jButton_SelectMember_ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Enable = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jSpinner_book = new javax.swing.JSpinner();
        jSpinner_Memberid = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_formtitle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_formtitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_formtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_formtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_formtitle.setText(" Issue Book ");
        jLabel_formtitle.setOpaque(true);

        jLabel_close.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_close.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enter Book Id:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Issue Date:");

        jButton_Issue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Issue.setText("Issue ");
        jButton_Issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IssueActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_SelectBook_.setText("Search book");
        jButton_SelectBook_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectBook_ActionPerformed(evt);
            }
        });

        jLabel_BookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_BookName.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_BookName.setText("Book Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Enter Member Id:");

        jLabel_MemberFullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_MemberFullName.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_MemberFullName.setText("Member full Name");

        jButton_SelectMember_.setText("Search member");
        jButton_SelectMember_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectMember_ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Is this Book available:");

        jLabel_Enable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Enable.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_Enable.setText("Yes or No");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Return Date:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Note:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_formtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton_Issue, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_MemberFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSpinner_book, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(jSpinner_Memberid))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_SelectBook_)
                                        .addComponent(jButton_SelectMember_)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Enable, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(457, 457, 457)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_formtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_SelectBook_)
                    .addComponent(jSpinner_book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BookName)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton_SelectMember_)
                    .addComponent(jSpinner_Memberid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_MemberFullName)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_Enable))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Issue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
      this.dispose();
    }                                         

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        this.dispose();
    }                                              

    private void jButton_IssueActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        
        int _book_id = (int)jSpinner_book.getValue();
        int _member_id = (int)jSpinner_Memberid.getValue();
        String _note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        try
        {
           String _issue_date = dateFormat.format(jDateChooser_IssueDate.getDate());
        String _return_date = dateFormat.format(jDateChooser_ReturnDate.getDate());
        
            Date issDate = dateFormat.parse(_issue_date);
        
        Date rtnDate = dateFormat.parse(_return_date);
        if(!book_Exist)
        {
           JOptionPane.showMessageDialog(null,"you need to Check if this book Exist","check if the book Exist",2);  
        } 
        else if(!member_Exist)
        {
           JOptionPane.showMessageDialog(null,"you need to Check if this book Exist","check if the book Exist",2);  
         
        }
            
        
        
      else  if(rtnDate.before(issDate))
        {
          JOptionPane.showMessageDialog(null,"The Return Date Must be after the issue date","Wrong Return Datr",2);  
        }
        else
        {
          issue.addIssue(_book_id,_member_id,"issued",_issue_date, _return_date,_note);  
        }
        
        
       
        }
        catch(HeadlessException |  NullPointerException | ParseException ex)
                {
                    JOptionPane.showMessageDialog(null,"Select issue date &return date","select Datr",2);
                }
        
       
        
    }                                             

    private void jButton_SelectBook_ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        int book_id = (int)jSpinner_book.getValue();
        
        
        
        try{
                my_classess.Book selectedBook = book.getBookById(book_id);
                if(selectedBook != null)
                {
                jLabel_BookName.setText(selectedBook.getName());
                book_Exist =true;
                
                if(issue.checkBookAvailability(book_id))
                {
                    jLabel_Enable.setText("yes");
                    
                }
                else 
                {
                  jLabel_Enable.setText("No");  
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"This Book Dosen't exist" ,"Book not Found",2);
                    book_Exist =false;
                }
        } catch (SQLException ex) 
        {
           Logger.getLogger(Book.class.getName()).log(Level.SEVERE, null, ex);
             
            
        }
        
        
    }                                                   

    private void jButton_SelectMember_ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        
               int member_id = (int)jSpinner_Memberid.getValue();
        
        
        
        try{
                my_classess.Member selectedMember = member.getMemberById(member_id);
                if(selectedMember!= null)
                {
                jLabel_MemberFullName.setText(selectedMember.getFirstName() + " "+selectedMember.getLastName());
                member_Exist = true;
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"This member Dosen't exist" ,"Member not Found",2);
                }
        } catch (SQLException ex) 
        {
           Logger.getLogger(Book.class.getName()).log(Level.SEVERE, null, ex);
             
            
        }

        
    }                                                     

    public static void displayAuthorData(int id,String fullName)
    {
        
         
    }
    
    
    
    public boolean verif()
    {
      return true;
    }
    
    public void fillJcomboboxWithGenres()
    {
       
           
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBookForm().setVisible(true);
            }
        });
    }
